import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Upload, FileText, Sparkles, ShieldCheck, UserRound, Stethoscope, Send, Share2, Activity, ChevronRight} from 'lucide-react';
import './style.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
const demoReport={documentType:'Sample Medical Report',date:'',summary:'Upload a PDF to generate a real Gemini-powered summary.',conditions:[],medications:[],findings:[],importantObservations:[],questionsForDoctor:[]};

function App(){
 const [page,setPage]=useState('dashboard'); const [role,setRole]=useState('patient'); const [file,setFile]=useState(null); const [report,setReport]=useState(null); const [busy,setBusy]=useState(false); const [question,setQuestion]=useState(''); const [answer,setAnswer]=useState(''); const [shared,setShared]=useState(false); const [error,setError]=useState('');
 const analyze=async()=>{if(!file)return;setBusy(true);setError('');setAnswer('');try{const fd=new FormData();fd.append('file',file);const r=await fetch(`${API}/analyze`,{method:'POST',body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error);setReport(j);setPage('record');}catch(e){setError(e.message)}finally{setBusy(false)}};
 const ask=async()=>{if(!question||!report)return;setBusy(true);setError('');try{const r=await fetch(`${API}/ask`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,report:report.data})});const j=await r.json();if(!r.ok)throw new Error(j.error);setAnswer(j.answer)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const nav=(p)=>{setPage(p);setError('')};
 return <div className="app"><aside><div className="brand"><div className="logo">S</div><div><b>SURAKSHIT</b><span>Your health. Your control.</span></div></div><div className="nav">{[['dashboard','Dashboard'],['records','My Records'],['assistant','AI Assistant'],['sharing','Sharing']].map(([id,label])=><button className={page===id?'active':''} onClick={()=>nav(id)} key={id}>{label}</button>)}</div><div className="role"><span>Demo role</span><button onClick={()=>setRole(role==='patient'?'doctor':'patient')}><span>{role==='patient'?<UserRound size={16}/>:<Stethoscope size={16}/>}</span>{role==='patient'?'Patient':'Doctor'} <ChevronRight size={15}/></button></div></aside><main><header><div><small>SECURE HEALTH CONTEXT</small><h1>{role==='patient'?'Understand your health.':'Authorized patient context.'}</h1></div><div className="pill"><ShieldCheck size={16}/> Consent-first</div></header>{error&&<div className="error">{error}</div>}{role==='doctor'?<Doctor report={report} shared={shared} />:<>{page==='dashboard'&&<Dashboard report={report} nav={nav}/>} {page==='records'&&<Records file={file} setFile={setFile} analyze={analyze} busy={busy} report={report} nav={nav}/>} {page==='record'&&<Record report={report} nav={nav}/>} {page==='assistant'&&<Assistant report={report} question={question} setQuestion={setQuestion} ask={ask} answer={answer} busy={busy}/>} {page==='sharing'&&<Sharing shared={shared} setShared={setShared}/>}</>}</main></div>
}
function Dashboard({report,nav}){return <div className="content"><section className="hero"><div><span className="eyebrow"><Sparkles size={14}/> GEMINI-POWERED</span><h2>Turn medical documents into <em>understandable context.</em></h2><p>Upload a report, let Gemini understand it, then ask questions grounded in your own record.</p><button className="primary" onClick={()=>nav('records')}>Upload a medical record <ChevronRight/></button></div><div className="heroCard"><Activity/><b>{report?'Record analyzed':'Ready for your first record'}</b><span>{report?'Gemini has extracted structured health information.':'Start with a PDF medical report.'}</span></div></section><div className="grid3"><Card title="My Records" value={report?'1':'0'} sub="documents analyzed"/><Card title="AI Context" value={report?'Ready':'—'} sub="record-grounded Q&A"/><Card title="Sharing" value="Private" sub="you control access"/></div><section className="panel"><div className="sectionHead"><div><small>HOW IT WORKS</small><h3>From document to health context</h3></div></div><div className="steps">{['Upload your report','Gemini understands it','Review the extracted context','Ask questions or share with your doctor'].map((x,i)=><div className="step" key={x}><b>0{i+1}</b><span>{x}</span></div>)}</div></section></div>}
function Card({title,value,sub}){return <div className="stat"><span>{title}</span><strong>{value}</strong><small>{sub}</small></div>}
function Records({file,setFile,analyze,busy,report,nav}){return <div className="content"><div className="titleRow"><div><small>MY MEDICAL RECORDS</small><h2>Upload a record</h2><p>For the live Gemini demo, use a PDF medical report.</p></div></div><label className="drop"><Upload size={28}/><b>{file?file.name:'Drop a PDF here or browse'}</b><span>PDF up to 20 MB</span><input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><div className="actions"><button className="primary" disabled={!file||busy} onClick={analyze}>{busy?<><span className="spinner"/> Gemini is analyzing…</>:<>Analyze with Gemini <Sparkles size={17}/></>}</button>{report&&<button className="secondary" onClick={()=>nav('record')}>View analyzed record</button>}</div><div className="privacy"><ShieldCheck size={19}/><div><b>Demo privacy boundary</b><span>The Gemini API key stays on the backend. Do not upload real patient records for a public hackathon demo.</span></div></div></div>}
function Record({report,nav}){if(!report)return <Empty nav={nav}/>;const d=report.data;return <div className="content"><div className="recordHead"><div className="docIcon"><FileText/></div><div><small>{d.documentType||'Medical document'}</small><h2>{report.fileName}</h2><span>Analyzed with {report.model}</span></div></div><section className="summary"><div className="sectionLabel"><Sparkles size={16}/> GEMINI SUMMARY</div><p>{d.summary}</p></section><div className="grid2"><section className="panel"><small>KEY FINDINGS</small><h3>Extracted results</h3>{d.findings?.length?<div className="findings">{d.findings.map((f,i)=><div className="finding" key={i}><div><b>{f.name}</b><span>{f.referenceRange||'Reference range not stated'}</span></div><strong>{f.value} {f.unit}</strong><i className={f.status}>{f.status?.replace('_',' ')}</i></div>)}</div>:<p className="muted">No structured test results were found.</p>}</section><section className="panel"><small>IMPORTANT OBSERVATIONS</small><h3>What to discuss</h3><ul>{(d.importantObservations?.length?d.importantObservations:['Ask Gemini about this report to explore its contents.']).map((x,i)=><li key={i}>{x}</li>)}</ul><button className="secondary wide" onClick={()=>nav('assistant')}>Ask about this record <Send size={16}/></button></section></div></div>}
function Assistant({report,question,setQuestion,ask,answer,busy}){return <div className="content"><div className="titleRow"><div><small>RECORD-GROUNDED AI</small><h2>Ask about your report</h2><p>Gemini answers using the extracted information from your uploaded record.</p></div></div>{report?<div className="context"><FileText size={17}/><span>Context: <b>{report.fileName}</b></span></div>:<div className="privacy"><ShieldCheck/><span>Upload and analyze a medical PDF first.</span></div>}<div className="suggestions">{['What are the important findings?','Which values are outside the reference range?','Explain this report in simple language.','What should I discuss with my doctor?'].map(q=><button onClick={()=>setQuestion(q)} key={q}>{q}</button>)}</div><div className="chat"><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask something about this record…"/><button className="primary" disabled={!report||!question||busy} onClick={ask}>{busy?'Thinking…':<>Ask Gemini <Send size={16}/></>}</button></div>{answer&&<div className="answer"><div className="aiBadge"><Sparkles size={15}/> GEMINI</div><p>{answer}</p><small>Source: {report.fileName}</small></div>}</div>}
function Sharing({shared,setShared}){return <div className="content"><small>SHARING & CONSENT</small><h2>Keep control of your health context.</h2><p>Choose what a doctor can access. This demo models the consent workflow.</p><div className="doctorCard"><div className="avatar">DS</div><div><b>Dr. Sharma</b><span>General Physician · City Hospital</span></div><div className="shareStatus">{shared?'Access active':'No access'}</div></div><div className="panel permissions"><h3>Information to share</h3><label><input type="checkbox" defaultChecked/> AI health summary</label><label><input type="checkbox" defaultChecked/> Selected medical reports</label><label><input type="checkbox"/> Complete medical history</label><button className={shared?'danger':'primary'} onClick={()=>setShared(!shared)}>{shared?'Revoke access':<>Share securely <Share2 size={16}/></>}</button></div></div>}
function Doctor({report,shared}){return <div className="content"><div className="doctorBanner"><Stethoscope/><div><small>DOCTOR VIEW</small><h2>Authorized patient context</h2><p>Only information explicitly shared by the patient is shown here.</p></div></div>{shared&&report?<Record report={report} nav={()=>{}}/>:<div className="empty"><ShieldCheck size={35}/><h3>No patient context shared</h3><p>Switch back to Patient, grant consent, then return here.</p></div>}</div>}
function Empty({nav}){return <div className="empty"><FileText/><h3>No record analyzed yet</h3><button className="primary" onClick={()=>nav('records')}>Upload a record</button></div>}
createRoot(document.getElementById('root')).render(<App/>);
